export const service = "Influencer Marketing";
export const openingMessage =
  "Hi! I see you're interested in Influencer Marketing. What's your name? Let's get started.";

export const serviceDetails = `Sub-types: Nano, Micro, Macro creators
Deliverables: Influencer sourcing, content coordination, performance tracking
Timelines: Short-term (1-4 weeks), Medium-term (1-3 months), Long-term (3+ months)
Pricing: Depends on creator size, content format, and usage rights.`;

export const questions = [
  {
    id: "Q1",
    nextId: "Q2",
    key: "name",
    answerType: "text",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["name", "call you", "full name"],
    templates: ["What's your name?"],
    suggestions: null,
    tags: ["name"],
  },
  {
    id: "Q2",
    nextId: "Q3",
    key: "platforms",
    answerType: "multi_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["platform", "instagram", "youtube", "linkedin"],
    templates: ["Which platform do you want to run influencer campaigns on? (multiple)"],
    suggestions: ["Instagram", "YouTube", "LinkedIn"],
    multiSelect: true,
  },
  {
    id: "Q3",
    nextId: "Q4",
    key: "influencer_size",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["size", "nano", "micro", "macro", "influencer size"],
    templates: ["What size of influencers do you want to work with?"],
    suggestions: [
      "Nano Influencers (1,000 – 10,000 followers)",
      "Micro Influencers (10,000 – 100,000 followers)",
      "Macro Influencers (100,000+ followers)",
    ],
  },
  {
    id: "Q4",
    nextId: "Q5",
    key: "campaign_objective",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["objective", "goal", "reach", "trust", "conversions", "sales"],
    templates: ["What is the main objective of the influencer campaign?"],
    suggestions: ["Brand reach", "Trust and credibility", "Conversions and sales"],
  },
  {
    id: "Q5",
    nextId: "Q6",
    key: "content_type",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["content", "reels", "videos", "posts", "stories"],
    templates: ["What type of content should influencers create?"],
    suggestions: ["Reels or videos", "Posts", "Stories", "A mix of formats -"],
  },
  {
    id: "Q6",
    nextId: "Q7",
    key: "niche_relevance",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["niche", "industry", "relevance"],
    templates: ["Is industry or niche relevance important?"],
    suggestions: ["Yes, niche-specific", "No, general creators are fine"],
  },
  {
    id: "Q7",
    nextId: "Q8",
    key: "target_geography",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["geography", "location", "local", "national", "international"],
    templates: ["Which geography should the influencers target?"],
    suggestions: ["Local", "National", "International"],
  },
  {
    id: "Q8",
    nextId: "Q9",
    key: "campaign_duration",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["duration", "timeline", "campaign length"],
    templates: ["How long should the campaign run?"],
    suggestions: ["Short-term", "Medium-term", "Long-term"],
  },
  {
    id: "Q9",
    nextId: "Q10",
    key: "usage_rights",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["usage", "rights", "content rights"],
    templates: ["Do you require usage rights for the content created?"],
    suggestions: ["Limited usage", "Full usage rights"],
  },
  {
    id: "Q10",
    nextId: null,
    key: "budget_range",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["budget", "range", "cost"],
    templates: ["What is your campaign budget range?"],
    suggestions: [
      "Under ₹10,000",
      "₹10,000 – ₹30,000",
      "₹30,000 – ₹75,000",
      "₹75,000 – ₹1,50,000",
      "₹1,50,000 and above",
    ],
  },
];

const chatbot = { service, openingMessage, questions, serviceDetails, skipIntro: true };
export default chatbot;
