export const service = "UGC (User-Generated Content) Marketing";
export const openingMessage =
  "Hi! I see you're interested in UGC (User-Generated Content) Marketing. What's your name? Let's get started.";

export const serviceDetails = `Sub-types: Customer testimonials, unboxing, reviews, product demos
Deliverables: UGC creator sourcing, content coordination, edits, usage rights
Timelines: Short-term (1-2 weeks), Standard (2-4 weeks), Ongoing monthly batches
Pricing: Depends on creator type, volume, and usage rights.`;

export const questions = [
  {
    id: "Q1",
    nextId: "Q2",
    key: "name",
    answerType: "text",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["name", "call you", "full name"],
    templates: ["What's your name?"],
    suggestions: null,
    tags: ["name"],
  },
  {
    id: "Q2",
    nextId: "Q3",
    key: "ugc_purpose",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["purpose", "goal", "ugc content", "brand"],
    templates: ["What is the main purpose of UGC content for your brand?"],
    suggestions: ["Paid ads", "Social proof", "Website content"],
  },
  {
    id: "Q3",
    nextId: "Q4",
    key: "usage_channels",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["used", "usage", "where", "channels"],
    templates: ["Where will this content be used?"],
    suggestions: ["Social media", "Advertising campaigns", "Website"],
  },
  {
    id: "Q4",
    nextId: "Q5",
    key: "creator_type",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["creator", "customers", "professional"],
    templates: ["What type of creators do you prefer?"],
    suggestions: ["Real customers", "Professional creators", "A mix of both"],
  },
  {
    id: "Q5",
    nextId: "Q6",
    key: "ugc_style",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["style", "scripted", "unscripted"],
    templates: ["What style of UGC do you prefer?"],
    suggestions: ["Natural and unscripted", "Fully scripted", "Semi-scripted"],
  },
  {
    id: "Q6",
    nextId: "Q7",
    key: "ugc_volume",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["how many", "quantity", "videos"],
    templates: ["How many UGC videos do you require?"],
    suggestions: ["1-5 Videos", "5-10 Videos", "10+ Videos"],
  },
  {
    id: "Q7",
    nextId: "Q8",
    key: "product_shipping",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["shipping", "product", "creators"],
    templates: ["Will product shipping be required for creators?"],
    suggestions: ["Yes", "No"],
  },
  {
    id: "Q8",
    nextId: "Q9",
    key: "revision_expectations",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["revisions", "changes"],
    templates: ["How many revisions do you expect?"],
    suggestions: ["Minimal", "Standard"],
  },
  {
    id: "Q9",
    nextId: "Q10",
    key: "usage_rights_duration",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["usage rights", "rights", "duration"],
    templates: ["How long do you need usage rights for the content?"],
    suggestions: ["Limited duration", "Extended duration"],
  },
  {
    id: "Q10",
    nextId: "Q11",
    key: "turnaround_time",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["turnaround", "timeline", "speed"],
    templates: ["What turnaround time do you prefer?"],
    suggestions: ["Fast", "Standard", "Flexible"],
  },
  {
    id: "Q11",
    nextId: null,
    key: "budget_level",
    answerType: "single_select",
    required: true,
    disableSharedContext: true,
    forceAsk: true,
    patterns: ["budget", "price", "per video"],
    templates: ["What budget level suits your requirement?"],
    suggestions: [
      "Under ₹2,000 per video",
      "₹2,000 – ₹5,000 per video",
      "₹5,000 – ₹10,000 per video",
      "₹10,000 and above per video",
    ],
  },
];

const chatbot = { service, openingMessage, questions, serviceDetails, skipIntro: true };
export default chatbot;
